FROM egifedcloud/bdii
MAINTAINER Enol Fernandez <enol.fernandez@egi.eu>

RUN yum install -y https://repos.fedorapeople.org/repos/openstack/openstack-liberty/rdo-release-liberty-5.noarch.rpm \
    && yum install -y git python-pip python-novaclient

RUN curl -L http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo > /etc/yum.repos.d/EGI-trustanchors.repo \
    && yum -y install ca-policy-egi-core \
    && cd /etc/pki/ca-trust/source/anchors \
    && ln -s /etc/grid-security/certificates/*.pem . \
    && update-ca-trust extract

RUN mkdir /cloud-bdii \
    && git clone --branch 0.6.0 https://github.com/EGI-FCTF/cloud-bdii-provider.git /cloud-bdii \
    && cd /cloud-bdii \
    && pip install .

COPY conf/bdii/cloud-bdii-provider /var/lib/bdii/gip/provider/cloud-info-provider
COPY conf/bdii/openstack.rc /etc/cloud-info-provider/openstack.rc
COPY conf/bdii/openstack.yaml /etc/cloud-info-provider/openstack.yaml
RUN chmod +x /var/lib/bdii/gip/provider/cloud-info-provider
