#!/bin/sh

if [ -r /etc/default/bdii ] ; then
    . /etc/default/bdii
fi
if [ -r /etc/sysconfig/bdii ] ; then
    . /etc/sysconfig/bdii
fi

BDII_CONF=${BDII_CONF:-/etc/bdii/bdii.conf}

if [ -f "${BDII_CONF}" ]; then
    . "${BDII_CONF}"
fi

LOCK_DIR=/var/lock/subsys
BDII_UPDATE=${BDII_UPDATE:-/usr/sbin/bdii-update}
BDII_CONF=${BDII_CONF:-/etc/bdii/bdii.conf}
UPDATE_LOCK_FILE=${UPDATE_LOCK_FILE:-${LOCK_DIR}/bdii-update}
SLAPD_LOCK_FILE=${SLAPD_LOCK_FILE:-${LOCK_DIR}/bdii-slapd}
UPDATE_PID_FILE=${BDII_PID_FILE:-/var/run/bdii/bdii-update.pid}
SLAPD_CONF=${SLAPD_CONF:-/etc/bdii/bdii-slapd.conf}


if [ -f "${SLAPD_LOCK_FILE}" ] || [ -f "${UPDATE_LOCK_FILE}" ] ; then
    echo "already started"
    exit 1
fi


export SLAPD_CONF=${SLAPD_CONF}
${BDII_UPDATE} -c ${BDII_CONF} -d

touch ${UPDATE_LOCK_FILE}
touch ${SLAPD_LOCK_FILE}

if [ ! -f ${UPDATE_PID_FILE} ]; then
    sleep 2
fi
if [ -f ${UPDATE_PID_FILE} ]; then
    PID=$(cat ${UPDATE_PID_FILE})
    ps ${PID} >/dev/null 2>&1
    RETVAL=$?
else
        exit 1
fi

while test -d "/proc/$PID"; do
    sleep 10 
done

rm ${UPDATE_LOCK_FILE} ${SLAPD_LOCK_FILE}

exit 0
