#!/bin/sh

cloud-info-provider-service --yaml /etc/cloud-info-provider/openstack.yaml \
                            --middleware openstack \
                            --os-username <user> --os-password <password> \
                            --os-tenant-name <tenant> --os-auth-url <auth_url> 
