#!/bin/sh

. /etc/cloud-info-provider/openstack.rc

GOCDB_SERVICE_TYPE=org.openstack.nova
GOCDB_URL="$OS_AUTH_URL"

# This may fail if the OS_AUTH_URL is not the one registered in GOC
GOCDB_ID=$(python -c "from __future__ import print_function; \
                      from cloud_info_provider.providers import gocdb; \
                      print(gocdb.find_in_gocdb('$GOCDB_URL', \
                                                '$GOCDB_SERVICE_TYPE')['gocdb_id'], end='')")

SITE_TOPIC=$(yq -r .site.name /etc/cloud-info-provider/openstack.yaml | tr "." "-")
AMS_TOPIC="SITE_${SITE_TOPIC}_ENDPOINT_${GOCDB_ID}"

cloud-info-provider-service --yaml /etc/cloud-info-provider/openstack.yaml \
                            --format glue21 \
                            --publisher ams \
                            --ams-cert "$HOSTCERT" \
                            --ams-key "$HOSTKEY" \
                            --ams-topic "$AMS_TOPIC" \
                            --middleware openstack
